name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      CUDA_VISIBLE_DEVICES: ""
      PYTHONWARNINGS: "ignore::UserWarning"
      # Force PyTorch to use CPU only
      FORCE_CUDA: "0"
      USE_CUDA: "0"
      PYTORCH_ENABLE_MPS_FALLBACK: "1"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        
    - name: Install dependencies
      run: |
        # Install CPU-only version of PyTorch before the rest of dependencies
        python -m pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
        # Disable virtualenv creation to avoid environment issues
        poetry config virtualenvs.create false
        poetry install
        
    - name: Lint with flake8
      run: |
        poetry run flake8 pneumonia_classifier scripts tests
        
    - name: Type check with mypy
      run: |
        poetry run mypy pneumonia_classifier scripts tests
        
    - name: Test with pytest
      run: |
        # Print PyTorch CUDA availability for debugging
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        echo "Running tests in CPU-only mode for PyTorch"
        poetry run pytest tests 